Bookshelf.WebUI/Models/User/UserLoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Bookshelf.WebUI.Models.User
{
    public class UserLoginViewModel
    {
        [Display(Name = "Kullanıcı Adınız"), Required(ErrorMessage = "Lütfen boş bırakmayın"), StringLength(50, ErrorMessage = "Kullanıcı adınız bu kadar uzun olamaz")]
        public string UserNickname { get; set; }
        [Display(Name = "Şifreniz"), DataType(DataType.Password), Required(ErrorMessage = "Lütfen boş bırakmayın"), StringLength(20, ErrorMessage = "Şifreniz bu kadar uzun olamaz")]
        public string UserPassword { get; set; }
    }
}

Bookshelf.WebUI/Models/User/UserModel.cs
using System.ComponentModel.DataAnnotations;

namespace Bookshelf.WebUI.Models.User
{
    public class UserModel
    {
        public int UserID { get; set; }
        [Display(Name = "Kullanıcı adı"), StringLength(50, ErrorMessage = "Lütfen {1} karakteri geçmeyin")]
        public string UserName { get; set; }
        [Display(Name = "Kullanıcı Soyadı"), StringLength(50, ErrorMessage = "Lütfen {1} karakteri geçmeyin")]
        public string UserSurname { get; set; }
        [Display(Name = "Kullanıcı Takma Ad"), StringLength(50, ErrorMessage = "Lütfen {1} karakteri geçmeyin")]
        public string UserNickname { get; set; }
        [MaxLength, Display(Name = "Kullanıcı Resim")]
        public string UserImg { get; set; }
        [Display(Name = "Kullanıcı Email"), DataType(DataType.EmailAddress, ErrorMessage = "Lütfen doğru Email adresi giriniz !"), StringLength(100, ErrorMessage = "Lütfen {1} karakteri geçmeyin")]
        public string UserEmail { get; set; }
        [Display(Name = "Kullanıcı şifre"), DataType(DataType.Password), StringLength(20, ErrorMessage = "Lütfen {1} karakteri geçmeyin")]
        public string UserNewPassword { get; set; }
        [Display(Name = "Kullanıcı şifre"), DataType(DataType.Password), StringLength(20, ErrorMessage = "Lütfen {1} karakteri geçmeyin")]
        public string UserPassword { get; set; }
        [Compare(nameof(UserPassword), ErrorMessage = "Şifre eşleşmiyor !"), Display(Name = "Kullanıcı şifre kontrol"), DataType(DataType.Password), StringLength(20, ErrorMessage = "Lütfen {0} karakteri geçmeyin")]
        public string UserPasswordControl { get; set; }

    }
}

Bookshelf.WebUI/Models/User/UserProfileViewModel.cs
namespace Bookshelf.WebUI.Models.User
{
    public class UserProfileViewModel
    {
        public UserModel User { get; set; }
    }
}

Bookshelf.WebUI/Models/User/UserRegisterViewModel.cs
namespace Bookshelf.WebUI.Models.User
{
    public class UserRegisterViewModel
    {
        public UserModel User { get; set; }
    }
}

Bookshelf.WebUI/Controllers/BookshelfController.cs
using Bookshelf.WebUI.Models.Bookshelf;
using Bookshelf.WebUI.Services.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Bookshelf.Entity.Entities;
using Bookshelf.ACore.Concrete;
using Bookshelf.ACore.Interface;
using Bookshelf.Business.Interface;

namespace Bookshelf.WebUI.Controllers
{
    public class BookshelfController : Controller
    {
        IUserSessionService _userSesssionService;
        IBookshelfService _bookshelfService;
        IAccessRoleService _accessRoleService;
        IBookService _bookService;

        public BookshelfController(IUserSessionService userSessionService, IBookshelfService bookshelfService, IAccessRoleService accessRoleService, IBookService bookService)
        {
            _userSesssionService = userSessionService;
            _bookshelfService = bookshelfService;
            _accessRoleService = accessRoleService;
            _bookService = bookService;

        }

        public IActionResult Index()
        {
            User user = _userSesssionService.UserGetSession();

            if (user != null)
            {
                ViewBag.title = user != null ? user.UserName + " " + user.UserSurname : "Woheap Anasayfa";

                var Bookshelf = _bookshelfService.GetAll(_userSesssionService.UserGetSession().UserId);

                var model = new BookshelfIndexViewModel
                {
                    bookshelfBooks = Bookshelf.Select(b => new BookshelfBook
                    {
                        Bookshelf = b,
                        Book = _bookService.GetAll(b.BookshelfID),
                    }).ToList()
                };

                return View(model);
            }
            else
            {
                return Redirect("/User/Login");
            }
        }


        [HttpGet]
        public IActionResult Add()
        {

            var model = new BookshelfAddViewModel
            {
                Bookshelf = new Entity.Entities.Bookshelf(),
                AccessRoles = _accessRoleService.GetSelectListAll()
            };

            ViewBag.title = model.Bookshelf.BookshelfName;
            ViewBag.description = model.Bookshelf.BookshelfExplain;

            return View(model);
        }

        [HttpPost]
        public IActionResult Add(Entity.Entities.Bookshelf bookshelf)
        {
            var model = new BookshelfAddViewModel
            {
                Bookshelf = bookshelf,
                AccessRoles = _accessRoleService.GetSelectListAll()
            };

            if (ModelState.IsValid)
            {
                bookshelf.User.UserId = _userSesssionService.UserGetSession().UserId;

                IReturnException<object> returnException = new ReturnException<object>();
                returnException = _bookshelfService.Add(bookshelf);

                if (returnException.Status)
                {
                    return Redirect("/Bookshelf/Index?status=" + returnException.Status + "&message=" + returnException.Message);
                }
                else
                {
                    var e = returnException.Exception;
                    return Redirect("/Bookshelf/Add?status=" + returnException.Status + "&message=" + returnException.Message);
                }
            }
            else
            {
                return View(model);
            }
        }



        [HttpGet]
        public IActionResult Update(int ID)
        {
            var model = new BookshelfUpdateViewModel
            {
                Bookshelf = _bookshelfService.Get(ID, _userSesssionService.UserGetSession().UserId),
                AccessRoles = _accessRoleService.GetSelectListAll()
            };

            ViewBag.title = model.Bookshelf.BookshelfName;
            ViewBag.description = model.Bookshelf.BookshelfExplain;

            if (model.Bookshelf != null && model.Bookshelf.User.UserId == _userSesssionService.UserGetSession().UserId)
            {
                return View(model);
            }
            else
            {
                return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");
            }

        }

        [HttpPost]
        public IActionResult Update(Entity.Entities.Bookshelf bookshelf)
        {
            IReturnException<object> returnException = new ReturnException<object>();

            //Kütüphane kullanıcı eşleşmesi
            Entity.Entities.Bookshelf control = _bookshelfService.Get(bookshelf.BookshelfID, _userSesssionService.UserGetSession().UserId);

            if (control != null)
            {
                if (ModelState.IsValid)
                {
                    bookshelf.User.UserId = _userSesssionService.UserGetSession().UserId;
                    returnException = _bookshelfService.Update(bookshelf);

                    if (returnException.Status)
                    {
                        return Redirect("/Bookshelf/Update/" + bookshelf.BookshelfID + "/?status=" + returnException.Status + "&message=" + returnException.Message);
                    }
                    else
                    {
                        return Redirect("/Bookshelf/Update/" + bookshelf.BookshelfID + "/?status=" + returnException.Status + "&message=" + returnException.Message);
                    }
                }
                else
                {
                    return View(bookshelf);
                }
            }
            else
            {
                return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");
            }



        }


    }
}

Bookshelf.WebUI/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Bookshelf.Entity.Entities;
using Bookshelf.WebUI.Models.User;
using Bookshelf.WebUI.Services.Abstract;
using Bookshelf.Business.Interface;
using Bookshelf.ACore.Interface;
using Bookshelf.ACore.Concrete;
using Microsoft.AspNetCore.Http;

namespace Bookshelf.WebUI.Controllers
{
    public class UserController : Controller
    {
        IUserSessionService _userSesssionService;
        IUserService _userService;
        IFileService _fileService;


        public UserController(IUserSessionService userSesssionService, IUserService userService, IFileService fileService = null)
        {
            _userSesssionService = userSesssionService;
            _userService = userService;
            _fileService = fileService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Register()
        {
            ViewBag.title = "Woheap kayıt ol";

            var model = new UserRegisterViewModel
            {
                User = new UserModel()
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Register(User user)
        {
            if (ModelState.IsValid)
            {
                IReturnException<object> returnRegister = new ReturnException<object>();
                User UserNicknameControl = _userService.getNickname(user.UserNickname);

                if (UserNicknameControl == null)
                {
                    returnRegister = _userService.Add(user);
                }
                else
                {
                    returnRegister.Message = UserNicknameControl.UserNickname + " zaten kullanılıyor !";
                    return Redirect("/User/Register?status" + returnRegister.Status + "&message=" + returnRegister.Message);
                }

                if (returnRegister.Status)
                {
                    returnRegister.SetReturnException(Status: true, Message: "Aramıza hoş geldin, giriş yapmaya hazırsın !", Data: user);
                    return Redirect("/User/Register?status=" + returnRegister.Status + "&message=" + returnRegister.Message);
                }
                else
                {
                    return Redirect("/User/Register?status=" + returnRegister.Status + "&message=" + returnRegister.Message);
                }
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult Login()
        {
            ViewBag.Title = "Woheap giriş";

            var model = new UserLoginViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Login(UserLoginViewModel User)
        {
            IReturnException<object> returnUserLogin = new ReturnException<object>();

            if (ModelState.IsValid)
            {
                returnUserLogin = _userService.UserLogin(User.UserNickname, User.UserPassword);

                if (returnUserLogin.Status)
                {
                    User user = (User)returnUserLogin.Data;
                    _userSesssionService.UserSetSession(user);
                    return Redirect("/Bookshelf/Index");
                }
                else
                {
                    return Redirect("/User/login?status=" + returnUserLogin.Status + "&message=" + returnUserLogin.Message);
                }
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult Logout()
        {
            _userSesssionService.UserRemoveSession();
            return Redirect("/User/Index");
        }

        [HttpGet]
        public IActionResult Profil()
        {
            User user = _userSesssionService.UserGetSession();

            var model = new UserProfileViewModel
            {
                User = new UserModel
                {
                    UserID = user.UserId,
                    UserEmail = user.UserEmail,
                    UserImg = user.UserImg,
                    UserName = user.UserName,
                    UserNickname = user.UserNickname,
                    UserPassword = user.UserPassword,
                    UserPasswordControl = user.UserPasswordControl,
                    UserSurname = user.UserSurname
                }
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult ProfilUpdate(UserModel User, IFormFile UserImg)
        {
            IReturnException<object> returnImagesException = new ReturnException<object>();
            IReturnException<object> returnException = new ReturnException<object>();

            User.UserID = _userSesssionService.UserGetSession().UserId;
            User UserReal = _userService.Get(User.UserID);
            if (ModelState.IsValid)
            {
                if (UserImg != null)
                {
                    returnImagesException = _fileService.FileUpload(UserImg, "/wwwroot/dimg/User", true, User.UserName);
                    if (returnImagesException.Status)
                    {
                        _fileService.FileRemove("/wwwroot/dimg/User/" + UserReal.UserImg, true);
                        UserReal.UserImg = returnImagesException.Data.ToString();
                    }
                }
                else
                {
                    returnImagesException.Status = true;
                }

                if (!string.IsNullOrEmpty(User.UserNewPassword))
                {
                    if (UserReal.UserPassword == User.UserPassword)
                    {
                        UserReal.UserPassword = User.UserNewPassword;
                    }
                }

                returnException = _userService.Update(UserReal);

                if (returnImagesException.Status)
                {
                    _userSesssionService.UserSetSession(UserReal);
                    return Redirect("/User/Profil/?status=" + returnException.Status + "&message=" + returnException.Message);
                }
                else
                {
                    return Redirect("/User/Profil/?status=" + returnException.Status + "&message=" + returnException.Message + "<br> Uyarı !: Resim yüklenemedi.");
                }
            }
            else
            {
                return View(UserReal);
            }

        }


    }
}

Bookshelf.WebUI/Views/User/Login.cshtml
@model Bookshelf.WebUI.Models.User.UserLoginViewModel;
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from www.urbanui.com/melody/template/pages/samples/register-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 15 Sep 2018 06:08:54 GMT -->
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.title</title>
    <meta name="description" content="@ViewBag.description" />
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/iconfonts/font-awesome/css/all.min.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.addons.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/favicon.png" />
</head>

<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-stretch auth auth-img-bg">
                <div class="row flex-grow">
                    <div class="col-lg-6 d-flex align-items-center justify-content-center">
                        <div class="auth-form-transparent text-left p-3">
                            <div class="brand-logo">
                                <img src="~/images/logo.png" alt="logo">
                            </div>
                            <h4>Hoş geldiniz</h4>
                            <warning status="@Context.Request.Query["status"]" title="Dikkat !" message="@Context.Request.Query["message"]"></warning>
                            <form class="pt-3" method="post" asp-controller="User" asp-action="Login">
                                <div class="form-group">
                                    <label asp-for="UserNickname"></label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="fa fa-user text-primary"></i>
                                            </span>
                                        </div>
                                        <input type="text" asp-for="UserNickname" class="form-control form-control-lg border-left-0" placeholder="Kullanıcı adı">
                                    </div>
                                    <span class="text-danger" asp-validation-for="UserNickname"></span>
                                </div>
                                
                                <div class="form-group">
                                    <label asp-for="UserPassword"></label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="fa fa-lock text-primary"></i>
                                            </span>
                                        </div>
                                        <input type="password" asp-for="UserPassword" class="form-control form-control-lg border-left-0" id="exampleInputPassword" placeholder="Şifre">
                                    </div>
                                    <span class="text-danger" asp-validation-for="UserPassword"></span>
                                </div>

                                <div class="mt-3">
                                    <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">Giriş</button>
                                </div>
                                <div class="text-center mt-4 font-weight-light">
                                    Henüz bir hesabım yok ? <a href="/User/Register" class="text-primary">Kayıt Ol</a>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-6 register-half-bg d-flex flex-row">
                        <p class="text-white font-weight-medium text-center flex-grow align-self-end">Copyright &copy; 2021 woheap tüm hakları saklıdır.</p>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/vendors/js/vendor.bundle.base.js"></script>
    <script src="~/vendors/js/vendor.bundle.addons.js"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="~/js/off-canvas.js"></script>
    <script src="~/js/hoverable-collapse.js"></script>
    <script src="~/js/misc.js"></script>
    <script src="~/js/settings.js"></script>
    <script src="~/js/todolist.js"></script>
    <!-- endinject -->
</body>


<!-- Mirrored from www.urbanui.com/melody/template/pages/samples/register-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 15 Sep 2018 06:08:54 GMT -->
</html>

Bookshelf.WebUI/Views/User/Profil.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Bookshelf.WebUI.Models.User.UserProfileViewModel;

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">@Model.User.UserName @Model.User.UserSurname</h4>
            <p class="card-description">
            </p>
            <warning title="Uyarı" message="@Context.Request.Query["message"]" status="@Context.Request.Query["status"]"></warning>
            <form class="forms-sample" asp-controller="User" asp-action="ProfilUpdate" method="POST" enctype="multipart/form-data">
                <div class="text-right">
                    <button type="submit" class="btn btn-danger btn-fw font-weight-bold text-white"><i class="fa fa-plus"></i> Güncelle</button>
                    <a asp-controller="Bookshelf" asp-action="Index" class="btn btn-light">İptal</a>
                </div>

                <div class="form-group">
                    <label asp-for="User.UserImg"></label>
                    <div class="mt-1 mb-1">
                        @{
                            if (String.IsNullOrEmpty(Model.User.UserImg))
                            {
                                <i class="fa fa-user"></i>
                            }
                            else
                            {
                                <img width="75px" src="~/dimg/User/@Model.User.UserImg" title="Eski Resim">
                            }
                        }
                    </div>
                    <input type="file" class="dropify" name="UserImg" />
                </div>

                <div class="form-group">
                    <label asp-for="User.UserNewPassword"></label>
                    <input type="text" class="form-control" asp-for="User.UserNewPassword">
                    <span class="text-danger" asp-validation-for="User.UserNewPassword"></span>
                </div>

                <div class="form-group">
                    <label asp-for="User.UserPasswordControl"></label>
                    <input type="text" class="form-control" asp-for="User.UserPasswordControl">
                    <span class="text-danger" asp-validation-for="User.UserPasswordControl"></span>
                </div>

                <div class="form-group">
                    <label asp-for="User.UserPassword"></label>
                    <input type="text" class="form-control" asp-for="User.UserPassword">
                    <span class="text-danger" asp-validation-for="User.UserPassword"></span>
                </div>

                <div class="text-right">
                    <button type="submit" class="btn btn-danger btn-fw font-weight-bold text-white"><i class="fa fa-plus"></i> Güncelle</button>
                    <a asp-controller="Bookshelf" asp-action="Index" class="btn btn-light">İptal</a>
                </div>

            </form>
        </div>
    </div>
</div>