Bookshelf.WebUI/Models/Book/BookAddModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Bookshelf.WebUI.Models.Book
{
    public class BookAddModel
    {
        [Required(ErrorMessage = "Lütfe Boş Geçmeyin !"), Display(Name = "Kitaplık")]
        public int BookshelfID { get; set; }
        [Required(ErrorMessage = "Lütfen Boş Geçmeyin !"), Display(Name = "Kitap Adı"), StringLength(100, ErrorMessage = "Lütren {1} karakteri geçmeyin !"), Column(TypeName = "varchar")]
        public string BookshelfName { get; set; }
        public string BookName { get; set; }
        [Display(Name = "Kitap Açıklama"), StringLength(300, ErrorMessage = "Lütfen {1} karakteri geçmeyin !")]
        public string BookExplain { get; set; }
    }
}

Bookshelf.WebUI/Models/Book/BookModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Bookshelf.WebUI.Models.Book
{
    public class BookModel
    {
        [Required(ErrorMessage = "Lütfe Boş Geçmeyin !")]
        public int BookID { get; set; }
        [Required(ErrorMessage = "Lütfe Boş Geçmeyin !"), Display(Name = "Kitaplık")]
        public int BookshelfID { get; set; }
        [Required(ErrorMessage = "Lütfen Boş Geçmeyin !"), Display(Name = "Kitap Adı"), StringLength(100, ErrorMessage = "Lütren {1} karakteri geçmeyin !")]
        public string BookName { get; set; }
        [Display(Name = "Kitap Açıklama"), StringLength(300, ErrorMessage = "Lütfen {1} karakteri geçmeyin !")]
        public string BookExplain { get; set; }
        public List<Entity.Entities.BookPage> BookPages { get; set; }
    }
}

Bookshelf.WebUI/Controllers/BookController.cs
using Bookshelf.ACore.Interface;
using Bookshelf.ACore.Concrete;
using Bookshelf.Business.Interface;
using Bookshelf.WebUI.Models.Book;
using Bookshelf.WebUI.Services.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace Bookshelf.WebUI.Controllers
{
    public class BookController : Controller
    {

        IBookshelfService _bookshelfService;
        IBookService _bookService;
        IUserSessionService _userSessionService;
        IBookPageService _bookPageService;

        public BookController(IBookshelfService bookshelfService, IUserSessionService userSessionService, IBookService bookService, IBookPageService bookPageService = null)
        {
            _bookshelfService = bookshelfService;
            _userSessionService = userSessionService;
            _bookService = bookService;
            _bookPageService = bookPageService;
        }

        [HttpGet,]
        public IActionResult Index(int ID)
        {
            Entity.Entities.Book book = _bookService.Get(ID);

            if (book != null)
            {
                Entity.Entities.Bookshelf bookshelf = _bookshelfService.Get(book.BookshelfID, _userSessionService.UserGetSession().UserId);
                if (bookshelf != null)
                {
                    var model = new BookModel
                    {
                        BookID = book.BookID,
                        BookName = book.BookName,
                        BookExplain = book.BookExplain,
                        BookshelfID = bookshelf.BookshelfID,
                        BookPages = _bookPageService.GetAll(book.BookID)
                    };

                    ViewBag.title = bookshelf.BookshelfName + " " + book.BookName;
                    ViewBag.description = book.BookExplain;
                    ViewBag.pageTitle1 = bookshelf.BookshelfName + " / " + book.BookName;

                    return View(model);
                }
            }

            return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");


        }

        [HttpGet]
        public IActionResult Add(int ID)
        {
            Entity.Entities.Bookshelf bookshelfControl = _bookshelfService.Get(ID, _userSessionService.UserGetSession().UserId);

            if (bookshelfControl != null)
            {
                var model = new BookAddModel
                {
                    BookshelfName = bookshelfControl.BookshelfName,
                    BookshelfID = bookshelfControl.BookshelfID
                };

                return View(model);
            }
            else
            {
                return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");
            }
        }

        [HttpPost]
        public IActionResult Add(BookAddModel book)
        {
            IReturnException<object> returnException = new ReturnException<object>();

            Entity.Entities.Bookshelf bookshelfControl = _bookshelfService.Get(book.BookshelfID, _userSessionService.UserGetSession().UserId);

            if (bookshelfControl != null)
            {
                if (ModelState.IsValid)
                {
                    Entity.Entities.Book Book = new Entity.Entities.Book
                    {
                        BookName = book.BookName,
                        BookExplain = book.BookExplain,
                        BookshelfID = bookshelfControl.BookshelfID,
                    };

                    returnException = _bookService.Add(Book);
                    if (returnException.Status)
                    {
                        return Redirect("/Bookshelf/Index/?status=" + returnException.Status + "&message=" + returnException.Message);
                    }
                    else
                    {
                        return Redirect("/Bookshelf/Index/?status=" + returnException.Status + "&message=" + returnException.Message);
                    }
                }
                else
                {
                    return View(book);
                }
            }
            else
            {
                return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");
            }

        }

        [HttpGet]
        public IActionResult Delete(int ID)
        {
            IReturnException<object> returnException = new ReturnException<object>();

            Entity.Entities.Book book = _bookService.Get(ID);

            if (book != null)
            {
                Entity.Entities.Bookshelf bookshelfControl = _bookshelfService.Get(book.BookshelfID, _userSessionService.UserGetSession().UserId);

                if (bookshelfControl != null)
                {
                    returnException = _bookService.Delete(book);
                    var r = returnException.Exception;
                    return Redirect("/Bookshelf/Index/?status=" + returnException.Status + "&message=" + returnException.Message);
                }

            }

            return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");

        }
    }
}

Bookshelf.WebUI/Controllers/BookPageController.cs
using Bookshelf.ACore.Interface;
using Bookshelf.ACore.Concrete;
using Bookshelf.Business.Interface;
using Bookshelf.WebUI.Models.BookPage;
using Bookshelf.WebUI.Services.Abstract;
using Microsoft.AspNetCore.Mvc;
using Bookshelf.Entity.Entities;

namespace Bookshelf.WebUI.Controllers
{
    public class BookPageController : Controller
    {
        IBookService _bookService;
        IBookPageService _bookPageService;
        IBookshelfService _bookshelfService;
        IUserSessionService _userSessionService;

        public BookPageController(IBookshelfService bookshelfService, IBookService bookService, IUserSessionService userSessionService = null, IBookPageService bookPageService = null)
        {
            _bookshelfService = bookshelfService;
            _bookService = bookService;
            _userSessionService = userSessionService;
            _bookPageService = bookPageService;
        }

        [HttpGet]
        public IActionResult Add(int ID)
        {
            IReturnException<object> returnException = new ReturnException<object>();

            Book book = _bookService.Get(ID);

            if (book != null)
            {
                Entity.Entities.Bookshelf bookshelfControl = _bookshelfService.Get(book.BookshelfID, _userSessionService.UserGetSession().UserId);

                if (bookshelfControl != null)
                {
                    returnException = _bookPageService.Add(new BookPage
                    {
                        BookID = book.BookID,
                        BookPageTitle = "Başlık",
                        BookPageText = "İçerik",
                    });

                    return Redirect("/Book/Index/" + book.BookID + "/?status=" + returnException.Status + "&message=" + returnException.Message);

                }
            }
            return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");

        }

        [HttpGet]
        public IActionResult Delete(int ID)
        {
            IReturnException<object> returnException = new ReturnException<object>();

            BookPage bookPage = _bookPageService.Get(ID);

            if (bookPage != null)
            {
                Book book = _bookService.Get(bookPage.BookID);

                if (book != null)
                {
                    Entity.Entities.Bookshelf bookshelf = _bookshelfService.Get(book.BookshelfID, _userSessionService.UserGetSession().UserId);

                    if (bookshelf != null)
                    {
                        returnException = _bookPageService.Delete(bookPage);

                        return Redirect("/Book/Index/" + book.BookID + "/?status=" + returnException.Status + "&message=" + returnException.Message);
                    }
                }
            }
            return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");
        }

        [HttpGet]
        public IActionResult Write(int ID)
        {
            BookPage bookPage = _bookPageService.Get(ID);
            if (bookPage != null)
            {

                Book book = _bookService.Get(bookPage.BookID);

                if (book != null)
                {
                    Entity.Entities.Bookshelf bookshelf = _bookshelfService.Get(book.BookshelfID, _userSessionService.UserGetSession().UserId);

                    if (bookshelf != null)
                    {
                        var model = new BookPageModel
                        {
                            BookPage = bookPage
                        };

                        ViewBag.title = book.BookName + "/ " + bookPage.BookPageTitle;
                        return View(model);
                    }
                }
            }
            return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");
        }

        [HttpPost]
        public IActionResult Write(BookPage bookPage)
        {
            IReturnException<object> returnException = new ReturnException<object>();

            if (ModelState.IsValid)
            {
                BookPage bookPageControl = _bookPageService.Get(bookPage.BookPageID);

                if (bookPageControl != null)
                {
                    Book BookControl = _bookService.Get(bookPageControl.BookID);
                    if (BookControl != null)
                    {
                        Entity.Entities.Bookshelf bookshelf = _bookshelfService.Get(BookControl.BookshelfID, _userSessionService.UserGetSession().UserId);

                        returnException = _bookPageService.Update(bookPage);

                        return Redirect("/BookPage/Write/" + bookPageControl.BookPageID + "/?status=" + returnException.Status + "&message=" + returnException.Message);

                    }
                }
                return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");
            }
            else
            {
                return View();
            }
        }

    }
}

Bookshelf.WebUI/Controllers/BookshelfController.cs
using Bookshelf.WebUI.Models.Bookshelf;
using Bookshelf.WebUI.Services.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Bookshelf.Entity.Entities;
using Bookshelf.ACore.Concrete;
using Bookshelf.ACore.Interface;
using Bookshelf.Business.Interface;

namespace Bookshelf.WebUI.Controllers
{
    public class BookshelfController : Controller
    {
        IUserSessionService _userSesssionService;
        IBookshelfService _bookshelfService;
        IAccessRoleService _accessRoleService;
        IBookService _bookService;

        public BookshelfController(IUserSessionService userSessionService, IBookshelfService bookshelfService, IAccessRoleService accessRoleService, IBookService bookService)
        {
            _userSesssionService = userSessionService;
            _bookshelfService = bookshelfService;
            _accessRoleService = accessRoleService;
            _bookService = bookService;

        }

        public IActionResult Index()
        {
            User user = _userSesssionService.UserGetSession();

            if (user != null)
            {
                ViewBag.title = user != null ? user.UserName + " " + user.UserSurname : "Woheap Anasayfa";

                var Bookshelf = _bookshelfService.GetAll(_userSesssionService.UserGetSession().UserId);

                var model = new BookshelfIndexViewModel
                {
                    bookshelfBooks = Bookshelf.Select(b => new BookshelfBook
                    {
                        Bookshelf = b,
                        Book = _bookService.GetAll(b.BookshelfID),
                    }).ToList()
                };

                return View(model);
            }
            else
            {
                return Redirect("/User/Login");
            }
        }


        [HttpGet]
        public IActionResult Add()
        {

            var model = new BookshelfAddViewModel
            {
                Bookshelf = new Entity.Entities.Bookshelf(),
                AccessRoles = _accessRoleService.GetSelectListAll()
            };

            ViewBag.title = model.Bookshelf.BookshelfName;
            ViewBag.description = model.Bookshelf.BookshelfExplain;

            return View(model);
        }

        [HttpPost]
        public IActionResult Add(Entity.Entities.Bookshelf bookshelf)
        {
            var model = new BookshelfAddViewModel
            {
                Bookshelf = bookshelf,
                AccessRoles = _accessRoleService.GetSelectListAll()
            };

            if (ModelState.IsValid)
            {
                bookshelf.User.UserId = _userSesssionService.UserGetSession().UserId;

                IReturnException<object> returnException = new ReturnException<object>();
                returnException = _bookshelfService.Add(bookshelf);

                if (returnException.Status)
                {
                    return Redirect("/Bookshelf/Index?status=" + returnException.Status + "&message=" + returnException.Message);
                }
                else
                {
                    var e = returnException.Exception;
                    return Redirect("/Bookshelf/Add?status=" + returnException.Status + "&message=" + returnException.Message);
                }
            }
            else
            {
                return View(model);
            }
        }



        [HttpGet]
        public IActionResult Update(int ID)
        {
            var model = new BookshelfUpdateViewModel
            {
                Bookshelf = _bookshelfService.Get(ID, _userSesssionService.UserGetSession().UserId),
                AccessRoles = _accessRoleService.GetSelectListAll()
            };

            ViewBag.title = model.Bookshelf.BookshelfName;
            ViewBag.description = model.Bookshelf.BookshelfExplain;

            if (model.Bookshelf != null && model.Bookshelf.User.UserId == _userSesssionService.UserGetSession().UserId)
            {
                return View(model);
            }
            else
            {
                return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");
            }

        }

        [HttpPost]
        public IActionResult Update(Entity.Entities.Bookshelf bookshelf)
        {
            IReturnException<object> returnException = new ReturnException<object>();

            //Kütüphane kullanıcı eşleşmesi
            Entity.Entities.Bookshelf control = _bookshelfService.Get(bookshelf.BookshelfID, _userSesssionService.UserGetSession().UserId);

            if (control != null)
            {
                if (ModelState.IsValid)
                {
                    bookshelf.User.UserId = _userSesssionService.UserGetSession().UserId;
                    returnException = _bookshelfService.Update(bookshelf);

                    if (returnException.Status)
                    {
                        return Redirect("/Bookshelf/Update/" + bookshelf.BookshelfID + "/?status=" + returnException.Status + "&message=" + returnException.Message);
                    }
                    else
                    {
                        return Redirect("/Bookshelf/Update/" + bookshelf.BookshelfID + "/?status=" + returnException.Status + "&message=" + returnException.Message);
                    }
                }
                else
                {
                    return View(bookshelf);
                }
            }
            else
            {
                return Redirect("/Bookshelf/Index?status=false&message=Kütüphaneye ulaşılamadı lütfen daha sonra tekrar deneyin !");
            }



        }


    }
}

Bookshelf.WebUI/Views/Book/Add.cshtml
@model Bookshelf.WebUI.Models.Book.BookAddModel;

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">@Model.BookshelfName Yeni kitap ekle</h4>
            <p class="card-description">
            </p>
            <form class="forms-sample" asp-controller="Book" asp-action="Add">
                <input asp-for="@Model.BookshelfName"  hidden/>
                <input type="text" asp-for="BookshelfID" value="@Model.BookshelfID" hidden/>
                <div class="text-right">
                    <button type="submit" class="btn btn-danger btn-fw font-weight-bold text-white"><i class="fa fa-plus"></i> Ekle</button>
                    <a asp-controller="Bookshelf" asp-action="Index" class="btn btn-light">İptal</a>
                </div>
                <div class="form-group">
                    <label asp-for="BookName"></label>
                    <input type="text" class="form-control" asp-for="BookName">
                    <span class="text-danger" asp-validation-for="BookName"></span>
                </div>

                <div class="form-group">
                    <label asp-for="BookExplain"></label>
                    <textarea class="form-control" asp-for="BookExplain" rows="4"></textarea>
                    <span class="text-danger" asp-validation-for="BookExplain"></span>
                </div>
                
                <div class="text-right">
                    <button type="submit" class="btn btn-danger btn-fw font-weight-bold text-white"><i class="fa fa-plus"></i> Ekle</button>
                    <a asp-controller="Bookshelf" asp-action="Index" class="btn btn-light">İptal</a>
                </div>

            </form>
        </div>
    </div>
</div>

Bookshelf.WebUI/Views/Book/Index.cshtml
@model Bookshelf.WebUI.Models.Book.BookModel;


<div>
    <div class="row">
        <div class="col-md-6">
            <h3 class="page-title">
                @ViewBag.pageTitle1
            </h3>
        </div>
        <div class="col-md-6">
            <div class="text-right mb-2">
                <a class="btn btn-light btn-fw font-weight-bold text-white" asp-controller="Bookshelf" asp-action="Index" title="Geri">
                    <i class="fa fa-reply"></i>
                </a>
                <button type="button" class="btn btn-inverse-danger btn-fw font-weight-bold text-white" data-toggle="modal" data-target="#pageAddModel"><i class="fa fa-plus text-danger"></i> Yeni Sayfa Ekle</button>
            </div>
        </div>
    </div>
</div>
<warning title="Uyarı" message="@Context.Request.Query["message"]" status="@Context.Request.Query["status"]"></warning>


<div class="card-body">
    <div class="row">
        <div class="col-12">
            <div class="row">
                @{int i = 1;}
                @foreach (var bookPage in Model.BookPages)
                {
                    <div class="col-md-2 col-12 mt-2 book-page-body">
                        <div class="head-book-page text-center">
                            <div class="pt-3">
                                <span class="book-page-title h4">@(i++). Sayfa</span>
                            </div>
                            <div class="pt-3">
                                <span class="book-page-desk mt-2 h6">@bookPage.BookPageTitle</span>
                            </div>
                        </div>
                        <div class="footer-book-page text-center">
                            <div class="btn-group mt-1" role="group">
                                <a class="btn btn-dark" asp-controller="BookPage" asp-action="Write" asp-route-ID="@bookPage.BookPageID" >Detay</a>
                                <a class="btn btn-primary btn-inverse-warning" asp-controller="BookPage" asp-action="Delete" asp-route-ID="@bookPage.BookPageID"><i class="fas fa-trash text-white"></i></a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


<!-- Modal starts -->

<div class="modal fade" id="pageAddModel" tabindex="-1" role="dialog" aria-labelledby="pageAddModel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel-2">@ViewBag.pageTitle1</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>@ViewBag.pageTitle1 @(Model.BookPages.Count()+1). sayfayı ekle.</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-inverse-danger btn-fw font-weight-bold text-white" asp-controller="BookPage" asp-action="Add" asp-route-ID="@Model.BookID">Evet</a>
                <button type="button" class="btn btn-light" data-dismiss="modal">İpal</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal Ends -->